/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface SwFilmDetails {
    'filmUrl': string;
  }
  interface SwFilmDetailsAttributes extends StencilHTMLAttributes {
    'filmUrl'?: string;
  }

  interface SwFilmList {}
  interface SwFilmListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'SwFilmDetails': Components.SwFilmDetails;
    'SwFilmList': Components.SwFilmList;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'sw-film-details': Components.SwFilmDetailsAttributes;
    'sw-film-list': Components.SwFilmListAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSwFilmDetailsElement extends Components.SwFilmDetails, HTMLStencilElement {}
  var HTMLSwFilmDetailsElement: {
    prototype: HTMLSwFilmDetailsElement;
    new (): HTMLSwFilmDetailsElement;
  };

  interface HTMLSwFilmListElement extends Components.SwFilmList, HTMLStencilElement {}
  var HTMLSwFilmListElement: {
    prototype: HTMLSwFilmListElement;
    new (): HTMLSwFilmListElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'sw-film-details': HTMLSwFilmDetailsElement
    'sw-film-list': HTMLSwFilmListElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sw-film-details': HTMLSwFilmDetailsElement;
    'sw-film-list': HTMLSwFilmListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
