/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface SwFilmDetails {
    /**
    * The id for the film
    */
    'filmId': number;
    /**
    * The URL for the film
    */
    'filmUrl': string;
  }
  interface SwFilmDetailsAttributes extends StencilHTMLAttributes {
    /**
    * The id for the film
    */
    'filmId'?: number;
    /**
    * The URL for the film
    */
    'filmUrl'?: string;
  }

  interface SwFilmList {}
  interface SwFilmListAttributes extends StencilHTMLAttributes {}

  interface SwPeopleList {}
  interface SwPeopleListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'SwFilmDetails': Components.SwFilmDetails;
    'SwFilmList': Components.SwFilmList;
    'SwPeopleList': Components.SwPeopleList;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'sw-film-details': Components.SwFilmDetailsAttributes;
    'sw-film-list': Components.SwFilmListAttributes;
    'sw-people-list': Components.SwPeopleListAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSwFilmDetailsElement extends Components.SwFilmDetails, HTMLStencilElement {}
  var HTMLSwFilmDetailsElement: {
    prototype: HTMLSwFilmDetailsElement;
    new (): HTMLSwFilmDetailsElement;
  };

  interface HTMLSwFilmListElement extends Components.SwFilmList, HTMLStencilElement {}
  var HTMLSwFilmListElement: {
    prototype: HTMLSwFilmListElement;
    new (): HTMLSwFilmListElement;
  };

  interface HTMLSwPeopleListElement extends Components.SwPeopleList, HTMLStencilElement {}
  var HTMLSwPeopleListElement: {
    prototype: HTMLSwPeopleListElement;
    new (): HTMLSwPeopleListElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'sw-film-details': HTMLSwFilmDetailsElement
    'sw-film-list': HTMLSwFilmListElement
    'sw-people-list': HTMLSwPeopleListElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sw-film-details': HTMLSwFilmDetailsElement;
    'sw-film-list': HTMLSwFilmListElement;
    'sw-people-list': HTMLSwPeopleListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
